server:
  port: 8002




spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://39.104.125.231:3306/db_jude?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true
      username: root
      password: root
   jpa:
     hibernate.ddl-auto: update
     show-sql: true
     #格式化sql语句
#     properties:
#       hibernate:
#         format_sql: true
   thymeleaf:
    cache: false