master:
  url: jdbc:mysql://26.3.2.197:3306/hr-police-report?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
  username: root
  password: root@123
  driver: com.mysql.jdbc.Driver
db1:
  url: jdbc:mysql://26.3.2.197:3306/upms_dev2?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
  username: root
  password: root@123
  driver: com.mysql.jdbc.Driver
AES:
  KEY: aaDJL2d9DfhLZO0z
  IV: 412ADDSSFA342442
  enabled: true
lanxin:
  reqUrl: http://nlx.nm.ydxxw
  grantType: client_credential
  appid: 524288-14811136
  secret: C9FB458E29CDCD72F9B0C48423F05FD5
  linkmsg: http://20.115.0.55:20031/app-nlx-hrcs/#/empower